### ISSUE TITLE
Clip images as input

### ISSUE THREAD

**Issue by rginjapan** [nuoxu/AKGVP#3]
Sorry, I think the code is not consistency with your paper, since the clip_scene has not been used in your code...
https://github.com/nuoxu/AKGVP/blob/19c9fb751f5cf9154557365a990ba790159a539b/models/AKGVP.py#L123C9-L123C71

**Comment by nuoxu** [comment]
https://github.com/xiaobaishu0097/ECCV-VN?tab=readme-ov-file
https://drive.google.com/file/d/1-Xyo6zQNn1I1CQ0m6DEM_ojUUx1NUU5l/view

**Comment by Suhao07** [comment]
Did you figure it out?
